apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://kube.telephone.org:6443
  name: us-east
contexts:
- context:
    cluster: us-east
    user: admin
  name: default
current-context: default
users:
- name: admin
  user:
    client-certificate: /etc/kubernetes/ssl/kubernetes.pem
    client-key: /etc/kubernetes/ssl/kubernetes-key.pem
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/kubernetes.pem
    client-key: /etc/kubernetes/ssl/kubernetes-key.pem
preferences: {}
